const games=[
{id:1,name:"Neon Horizon",genre:"Action",price:999,old:1499,rating:4.8,cover:"images/games/neon-horizon.svg"},
{id:2,name:"Kingdoms of Eldoria",genre:"RPG",price:1299,old:1799,rating:4.9,cover:"images/games/eldoria.svg"},
{id:3,name:"Velocity X",genre:"Racing",price:799,old:1199,rating:4.6,cover:"images/games/velocity-x.svg"},
{id:4,name:"Shadow Protocol",genre:"Horror",price:1099,old:1599,rating:4.7,cover:"images/games/shadow-protocol.svg"},
{id:5,name:"Street Legends",genre:"Sports",price:699,old:999,rating:4.5,cover:"images/games/street-legends.svg"},
{id:6,name:"Empire Tactics",genre:"Strategy",price:899,old:1299,rating:4.8,cover:"images/games/empire-tactics.svg"},
{id:7,name:"Cyber Samurai",genre:"Action",price:1199,old:1699,rating:4.7,cover:"images/games/cyber-samurai.svg"},
{id:8,name:"Mystic Realms",genre:"RPG",price:999,old:1499,rating:4.6,cover:"images/games/mystic-realms.svg"}];
const get=(k,d)=>JSON.parse(localStorage.getItem(k)||JSON.stringify(d));const set=(k,v)=>localStorage.setItem(k,JSON.stringify(v));let cart=get("cart",[]),wishlist=get("wishlist",[]),library=get("library",[]);const money=n=>"₹"+n.toLocaleString("en-IN");
function updateCount(){document.querySelectorAll("#cartCount").forEach(e=>e.textContent=cart.length)}
function card(g){return `<article class="game-card"><div class="game-cover"><img src="${g.cover}" alt="${g.name} cover"></div><div class="game-info"><h3>${g.name}</h3><div class="meta">${g.genre} · ⭐ ${g.rating}</div><div class="price-row"><span class="price">${money(g.price)}</span><span class="old">${money(g.old)}</span></div><div class="card-actions"><button class="small-btn buy" onclick="addCart(${g.id})">Add to Cart</button><button class="small-btn heart" onclick="toggleWish(${g.id})">${wishlist.includes(g.id)?"❤️":"♡"}</button></div></div></article>`}
function render(el,arr){if(el)el.innerHTML=arr.length?arr.map(card).join(""):`<div class="empty">No games found.</div>`}function addCart(id){if(!cart.includes(id)){cart.push(id);set("cart",cart);updateCount();alert("Game added to cart!")}else alert("This game is already in your cart.")}function toggleWish(id){wishlist=wishlist.includes(id)?wishlist.filter(x=>x!==id):[...wishlist,id];set("wishlist",wishlist);location.reload()}
function store(){let el=document.getElementById("allGames");if(!el)return;let q=(document.getElementById("searchInput")?.value||"").toLowerCase(),genre=document.getElementById("genreFilter")?.value||"All",sort=document.getElementById("sortFilter")?.value||"featured",arr=games.filter(g=>g.name.toLowerCase().includes(q)&&(genre==="All"||g.genre===genre));if(sort==="low")arr.sort((a,b)=>a.price-b.price);if(sort==="high")arr.sort((a,b)=>b.price-a.price);if(sort==="rating")arr.sort((a,b)=>b.rating-a.rating);render(el,arr)}
function cartPage(){let el=document.getElementById("cartItems");if(!el)return;if(!cart.length){el.innerHTML='<div class="empty">Your cart is empty.<br><br><a class="btn primary" href="games.html">Browse Games</a></div>';return}let arr=games.filter(g=>cart.includes(g.id));el.innerHTML=arr.map(g=>`<div class="cart-row"><div class="cart-cover"><img src="${g.cover}" alt=""></div><div class="grow"><strong>${g.name}</strong><div class="meta">${g.genre}</div></div><strong>${money(g.price)}</strong><button class="small-btn" onclick="removeCart(${g.id})">Remove</button></div>`).join("");let sub=arr.reduce((s,g)=>s+g.price,0),old=arr.reduce((s,g)=>s+g.old,0);document.getElementById("subtotal").textContent=money(old);document.getElementById("discount").textContent="-"+money(old-sub);document.getElementById("total").textContent=money(sub)}
function removeCart(id){cart=cart.filter(x=>x!==id);set("cart",cart);updateCount();cartPage()}
document.getElementById("searchInput")?.addEventListener("input",store);document.getElementById("genreFilter")?.addEventListener("change",store);document.getElementById("sortFilter")?.addEventListener("change",store);
const p=new URLSearchParams(location.search);if(p.get("genre")&&document.getElementById("genreFilter"))document.getElementById("genreFilter").value=p.get("genre");
document.getElementById("checkoutForm")?.addEventListener("submit",e=>{e.preventDefault();library=[...new Set([...library,...cart])];set("library",library);cart=[];set("cart",cart);alert("Order placed! Your games are now in My Library.");location.href="library.html"});document.getElementById("loginForm")?.addEventListener("submit",e=>{e.preventDefault();alert("Demo login successful!");location.href="index.html"});document.getElementById("registerForm")?.addEventListener("submit",e=>{e.preventDefault();alert("Demo account created!");location.href="login.html"});document.getElementById("contactForm")?.addEventListener("submit",e=>{e.preventDefault();alert("Thanks! Your message has been submitted.");e.target.reset()});
updateCount();render(document.getElementById("featuredGames"),games.slice(0,4));store();render(document.getElementById("wishlistGames"),games.filter(g=>wishlist.includes(g.id)));cartPage();let lib=document.getElementById("libraryGames");if(lib){let arr=games.filter(g=>library.includes(g.id));lib.innerHTML=arr.length?arr.map(card).join(""):"<div class='empty'>Your library is empty. Purchase a game to see it here.</div>"}
